### ISSUE TITLE
Parttern doesn't match files in .tfsignore

### ISSUE THREAD

**Issue by latop2604** [madskristensen/IgnoreFiles#2]
### Installed product versions
- Visual Studio: 2015 Enterprise update 2
- This extension: 1.0.19
### Description

In .tfsignore, the pattern 'xxx' (ex: '.vs', 'packages', 'mycustomdirectory')  is displayed as grey color with tool-tip message 'The path 'x' does not point to any existing file. But in Team Explorer it work as expected.
### Steps to recreate
1. In a web project, add files in App_Data\xxx
2. in .tfsingore add 'xxx' pattern 
   or
3. Add a nuget packages to a project
4. in .tfsingore add 'packages' pattern 
### Current behavior

The pattern doesn't match anything
### Expected behavior

The pattern should match files in App_Data\xxx

**Comment by madskristensen** [comment]
This should be fixed in the latest version. Can you please try to update the extension and see if it's fixed?

**Comment by madskristensen** [comment]
@latop2604 This should be fixed in the latest version. Can you please try to update the extension and see if it's fixed?

**Comment by latop2604** [comment]
Thx, this issue is fixed.
