### ISSUE TITLE
Subversion ignore

### ISSUE THREAD

**Issue by rafakwolf** [madskristensen/IgnoreFiles#3]
Add subversion ignore

**Comment by madskristensen** [comment]
I didn't think SVN had a .ignore file. Do you have a link to the docs?

**Comment by madskristensen** [comment]
Or do people just use .svnignore like what is described [in this article](http://sethholloway.com/svnignore-example-for-java/)?

**Comment by rafakwolf** [comment]
Yes, using this command **'svn propset svn:ignore -R -F .svnignore .'** you can ignore files, but, it is not by default like git. :(

Thanks
